name: Maintain GitHub Streak

on:
 schedule:
   - cron: "45 17 * * *"  # 5:45 PM UTC
   - cron: "15 18 * * *"  # 6:15 PM UTC
   - cron: "30 19 * * *"  # 7:30 PM UTC
 workflow_dispatch:

jobs:
 streak:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       
     - name: Check if already ran today
       id: check
       run: |
         TODAY=$(date +%Y-%m-%d)
         if [ -f "last_run.txt" ]; then
           LAST_RUN=$(cat last_run.txt)
           if [ "$LAST_RUN" = "$TODAY" ]; then
             echo "already_ran=true" >> $GITHUB_OUTPUT
           else
             echo "already_ran=false" >> $GITHUB_OUTPUT
           fi
         else
           echo "already_ran=false" >> $GITHUB_OUTPUT
         fi
         
     - name: Generate daily commit count
       if: steps.check.outputs.already_ran == 'false'
       id: random
       run: |
         # Random commits: 2(25%), 3(50%), 4(25%)
         RAND=$((RANDOM % 100))
         if [ $RAND -lt 25 ]; then
           COMMIT_COUNT=2
         elif [ $RAND -lt 75 ]; then
           COMMIT_COUNT=3
         else
           COMMIT_COUNT=4
         fi
         echo "commits=$COMMIT_COUNT" >> $GITHUB_OUTPUT
         
         # Mark today as completed
         TODAY=$(date +%Y-%m-%d)
         echo "$TODAY" > last_run.txt
         
     - name: Auto Streak Keeper
       if: steps.check.outputs.already_ran == 'false'
       uses: bmiit145/auto-streak-keeper@v1.0.2
       with:
         user-name: ${{ github.actor }}
         user-email: ${{ secrets.USER_EMAIL }}
         github-token: ${{ secrets.GITHUB_TOKEN }}
         min-commits: ${{ steps.random.outputs.commits }}
         max-commits: ${{ steps.random.outputs.commits }}
         branch-name: main
         commit-message: "Auto-commit"
