name: Maintain GitHub Streak

on:
  schedule:
    # Multiple random times throughout the day (UTC)
    - cron: "15 2 * * *"   # 2:15 AM UTC
    - cron: "45 7 * * *"   # 7:45 AM UTC  
    - cron: "30 12 * * *"  # 12:30 PM UTC
    - cron: "20 16 * * *"  # 4:20 PM UTC
    - cron: "50 20 * * *"  # 8:50 PM UTC
  workflow_dispatch:

jobs:
  streak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate random commit count
        id: random
        run: |
          # Generate random number between 2-5
          COMMIT_COUNT=$((RANDOM % 4 + 2))
          echo "commits=$COMMIT_COUNT" >> $GITHUB_OUTPUT
          
          # Random chance to skip this run (30% chance to skip)
          SKIP_CHANCE=$((RANDOM % 10))
          if [ $SKIP_CHANCE -lt 3 ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Auto Streak Keeper
        if: steps.random.outputs.skip == 'false'
        uses: bmiit145/auto-streak-keeper@v2
        with:
          user-name: ${{ github.actor }}
          user-email: ${{ secrets.GITHUB_USER_EMAIL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          min-commits: ${{ steps.random.outputs.commits }}
          max-commits: ${{ steps.random.outputs.commits }}
          branch-name: main
          commit-message: "Auto-commit"